[theme]
primaryColor = "#15d5ee" # Accent color for interactive elements
backgroundColor = "#055055" # Main background color
secondaryBackgroundColor = "#065d63" # Sidebar background color
textColor = "#f3eced" # Text color
font = "sans serif" # Font style (options: 'serif', 'sans serif', 'monospace')